# Generated by Django 3.1.4 on 2022-07-25 05:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='follow_author',
        ),
        migrations.AddField(
            model_name='book',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='static/livros/uploads/%Y/%m/%d/'),
        ),
    ]
