# Generated by Django 3.1.4 on 2022-07-25 06:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='static/categoria/uploads/%Y/%m/%d/')),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('meta_description', models.TextField(blank=True, max_length=160, null=True)),
                ('keywords', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web'),
        ),
    ]
