# Generated by Django 3.1.4 on 2022-07-25 05:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220725_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
